name: Test React

on: [push]

jobs:
  uno:
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje
        run: echo "Hello World"
        
      - name: Touch file
        run: |
          touch hola.txt
          ls -al
          
      - name: Set text
        run: |
          echo "hola" > hola.txt
          ls -al
          
      - name: Read File
        run: cat hola.txt
        
  dos:
    runs-on: ubuntu-latest
    needs: [uno]
    steps:
      - name: Directorio
        run: ls -al
